config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :participations
  resources :events
  resources :users, only: [:index, :show, :edit, :update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"
end

app/models/participation.rb
class Participation < ApplicationRecord
  # after_create :confirmation_send

  def confirmation_send
    ParticipationMailer.confirmation_email(self.user).deliver_now
  end

  belongs_to :user
  belongs_to :event
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: %i[ show edit update destroy ]

  # GET /participations or /participations.json
  def index
    @participations = Participation.all
  end

  # GET /participations/1 or /participations/1.json
  def show
  end

  # GET /participations/new
  def new
    @participation = Participation.new
  end

  # GET /participations/1/edit
  def edit
  end

  # POST /participations or /participations.json
  def create
    @participation = Participation.new(participation_params)

    respond_to do |format|
      if @participation.save
        format.html { redirect_to participation_url(@participation), notice: "Participation was successfully created." }
        format.json { render :show, status: :created, location: @participation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participations/1 or /participations/1.json
  def update
    respond_to do |format|
      if @participation.update(participation_params)
        format.html { redirect_to participation_url(@participation), notice: "Participation was successfully updated." }
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participations/1 or /participations/1.json
  def destroy
    @participation.destroy

    respond_to do |format|
      format.html { redirect_to participations_url, notice: "Participation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participation
      @participation = Participation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def participation_params
      params.require(:participation).permit(:stripe_customer_id, :user_id, :event_id)
    end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/_form.html.erb
<%= form_with(model: participation) do |form| %>
  <% if participation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

      <ul>
        <% participation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :stripe_customer_id, style: "display: block" %>
    <%= form.text_field :stripe_customer_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :event_id, style: "display: block" %>
    <%= form.text_field :event_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/participations/_participation.html.erb
<div id="<%= dom_id participation %>">
  <p>
    <strong>Stripe customer:</strong>
    <%= participation.stripe_customer_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= participation.user_id %>
  </p>

  <p>
    <strong>Event:</strong>
    <%= participation.event_id %>
  </p>

</div>

app/views/participations/edit.html.erb
<h1>Editing participation</h1>

<%= render "form", participation: @participation %>

<br>

<div>
  <%= link_to "Show this participation", @participation %> |
  <%= link_to "Back to participations", participations_path %>
</div>

app/views/participations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Participations</h1>

<div id="participations">
  <% @participations.each do |participation| %>
    <%= render participation %>
    <p>
      <%= link_to "Show this participation", participation %>
    </p>
  <% end %>
</div>

<%= link_to "New participation", new_participation_path %>

app/views/participations/new.html.erb
<h1>New participation</h1>

<%= render "form", participation: @participation %>

<br>

<div>
  <%= link_to "Back to participations", participations_path %>
</div>

app/views/participations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @participation %>

<div>
  <%= link_to "Edit this participation", edit_participation_path(@participation) %> |
  <%= link_to "Back to participations", participations_path %>

  <%= button_to "Destroy this participation", @participation, method: :delete %>
</div>