config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :participations
  resources :events
  resources :users, only: [:index, :show, :edit, :update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Event Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container navbar-brand">
      <%= link_to "My Event Manager" , events_path , class: "navbar-brand" %>
      
      </div>

      <div class="container">
      
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav m-1">
            
            
            <% if current_user == nil %>
              <li class="nav-item active m-1">
                <%= link_to "Se connecter" , new_user_session_path, class: "nav-link" %>
              </li>
            
              <li class="nav-item active m-1">
                <%= link_to "S'inscrire" , new_user_registration_path, class: "nav-link" %>
              </li>
            <% else %>
              
                  <li class="nav-item active m-1"><%= link_to "Mon profil", user_path(current_user), class: "nav-link" %></li>
                  <li class="nav-item active m-1"><%= link_to "Modifier mes informations", edit_user_path(current_user) , class:"nav-link" %></li>
                  <li class="nav-item active m-1"><%= link_to "Modifier mes identifiants", edit_user_registration_path , class:"nav-link" %></li>
                  <li class="nav-item active m-1"><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir vous déconnecter ?' }, class:"nav-link"%></li>
              
            <% end %>
            <% unless current_user == nil %>
            
            <% end %>
            
            
                <li class="nav-item active m-1"><%= link_to "Evenements" , events_path , class: " nav-link" %></li>
                <li class="nav-item active m-1"><%= link_to "Utilisateurs" , users_path , class: "  nav-link" %></li>
              
            
          </ul>
        
      </div>
      </div>
    </nav>
     <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>